// <auto-generated />
namespace ResturantSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_table_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_table_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202205250157183_added_table_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
