//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountTable
    {
        public int Id { get; set; }
        public string FoodCategory { get; set; }
        public string ProductName { get; set; }
        public string OfferPercent { get; set; }
        public string Detail { get; set; }
    }
}
